[image/visp] Upgrade to 2.6.1
ViSP 2.6.1 (released October 20th, 2011)
  - New features
     - Introduction of Lapack support used for the SVD decomposition in
     vpMatrix
     - Introduction of vpAROgre that enables augmented reality applications
       based on Ogre 3D. Some examples are provided in examples/ogre-simulator
     - Add cylinder's tracking in the model-based tracker.
     - Reintroduce OpenCV 2.0.0 support lost in ViSP 2.6.0
     - Introduction of vpKinect, a wrapper of libfreenect to support the
       Kinect device
     - Introduction of vpMoment and vpFeatureMoment classes to be able to
       consider 2D image moments as visual feature in visual servoing
  - Improvements
     - For firewire cameras framegrabbing with vp1394TwoGrabber, it is now
       possible to select a specific camera with its GUID by using setCamera()
     - All the specific Xml parser (vpMbtXmlParser, vpXmlParserCamera)
       inherit now from vpXmlParser
     - Memory leaks suppression in vpWireFrameSimulator, vpMe, vpXmlParser,
       vpMbtXmlParser, vpXmlParserCamera, vpMbTracker, vpFeatureLuminance,
       vpRobotSimulator, vpFFMPEG, vpBSpline
     - It is now possible to grab images from an usb webcam with the
       vpV4l2Grabber class that is based on the video 4 linux 2 driver.
     - When it was possible without braking the backward compatibilty
       std::list was introduced instead of vpList. Some of the functions that
       use vpList are now deprecated.
     - Better detection of image or video file types when used in vpImageIo,
       vpVideoReader and vpVideoWriter
  - Build
     - Set the build type by default to release
     - Improve the usage of debug versus release third-party libraries
  - Deprecated
     - vpAdaptativeGain is deprecated. Use vpAdaptiveGain instead.
     - vp1394Grabber is deprecated. Use vp1394TwoGrabber instead.
     - Most of the methods that use vpList are deprecated. Use std::list
     instead
     - vpTwistMatrix deprecated in ViSP-1.6.0 was removed.
  - Examples:
    - New example grabOpenCV-2.cpp to show how to use the OpenCV
      cv::VideoCapture class. This example shows how to acquire an image
      with cv::VideoCapture, how to transform this image in ViSP format
      and how to display it.
    - New examples to illustrate the usage of the Ogre simulator through
      vpAROgre class.
    - New example to illustrate the usage of the Kinect through
      vpKinect class.
    - New examples to illustrate the usage of 2D image moments.
  - Bug fixed
     - [11110] On OSX vpDisplayOpenCV does not display images since OpenCV
     2.1.0
     - [11147] Coin not installed, cannot read VRML files
     - [11473] vpImageTools::flip() come out error when deal with vpImage
       with vpRGBa type
     - [11529] ViSP / OpenCV(2.2.0) incompatibility
     - [11563] segfault in vpVideoReader
     - [11617] selecting a subset of features is not taken into account in
       vpServo
     - [11916] Build issues with GTK2 on ubuntu 10.10 (fatal error:
       gdk-pixbuf/gdk-pixbuf.h)
     - [11924] svdNr fails on some matrices where svdGsl succeeds
     - [11942] Build issues with GSL on OSX due to 32/64 bits architecture
     - [11943] Build issues with libjpeg on OSX due to 32/64 bits architecture
     - [11944] Build issues with libpng on OSX due to 32/64 bits architecture
     - [11981] vpV4l2Grabber class based on video 4 linux 2 is not able to
       grab images from an usb webcam
     - [12329] Bad font problem when opening vpPlot example
     - [12334] Under windows, link errors when some 3rd party libs are not
       build in the same build configuration as ViSP
     - [12499] servoSimu4Points: World point disposition does not match camera
     - [12591] Seg fault when using setCleanPreviousImage() from
       vpImageSimulator
     - [12739] Problem initialising a vpMeEllipse
     - [13014] Bug in vpCalibration::calibVVSMulti() jacobian
     - [13015] vpFFMPEG compatibility issue with ffmpeg-0.8 release
     - [13449] "LIBJPEG_BUILD_TEST - Failed" message in CMake for Visual 2010
     - [13467] CreateWindow windows API does not correctly register class.
----------------------------------------------
ViSP 2.6.0 (released September 23rd, 2010)
  - License:
      Change the open source license from QPL to GPL v2
  - New Features
    - Introduction of a new wireframe simulator. See vpWireFrameSimulator
    class.
    - Introduction of a new model-based tracker that allows to track
      an object based on its 3D model. See vpMbEdgeTracker class.
    - New vpForceTwistMatrix class that allows to transfer a force/torque skew
      from one frame to another.
    - New vpVelocityTwistMatrix class that allows to transfer a velocity skew
      from one frame to an other. The vpTwistMatrix class that does the same
      work previously is from now deprecated.
    - New vpRobotCycab class to communicate with the Cycab car-like mobile
      robot at Inria.
    - New generic vpRobotSimulator class to create robot simulators.
    - New vpSimulatorViper850 class which simulates the viper850 robot.
    - New vpSimulatorAfma6 class which simulates the Afma 6dof robot.
    - New vpPlanarObjectDetector class to detect a planar surface based on
      the Ferns Classifier.
    - New vpSickLDMRS class, a UNIX driver to get measures from a Sick LD-MRS
      laser scanner.
    - New vpPlot class that was recoded to suppress the XPlotter dependency.
      This class aims real time drawing of 2D or 3D graphics under Linux, OSX
      and Windows.
  - Third party library dependencies
    - OpenCV 1.1 and 2.0 are no more supported. ViSP requires at least
      OpenCV 2.1.
    - libplotter is no longer required.
    - Itifg8 is no longer supported.
  - Improvements
    - Copy constructors were added to better support stl lists and vectors.
    - In firewire framegrabbing using vp1394TwoGrabber based on libdc1394-2.x,
      add possibility to change during the execution the shutter, the gain, the
      brightness, ... (see documentation for more details)
      . new setIsoTransmissionSpeed(), setAutoShutter() methods
    - In vpThetaUVector addition of &operator=() method to initialise all the
      angles to the same value
    - In vpHomogeneousMatrix addition of
      . eye() method to set the transformation as identity
      . extract(vpThetaUVector &) to extract the rotation as a Theta U vector
    - In vpRobotViper850 add openGripper() and closeGripper() functions to
      control the Schunk two fingers electric gripper (available only at
      Inria).
    - In vpRotationVector and vpTranslationVector introduction of set()
      method that allows initialization from 3 doubles
    - Documentation improvements
  - Deprecated
      . Some deprecated classes were removed: vpItifg8Grabber,
        vpEulerVector, vpSubPixel, vpRA
      . Deprecated functions since ViSP 2.4.4 where also removed
  - Examples:
    - New example calibrateTsai.cpp to show how to use the vpCalibration
      class to estimate the hand to eye transformation.
    - New examples to illustrate the usage of the new wire-frame simulators
  - Bug fixed
    - [9476] Memory leak in vpImageIo::readPNG() functions.
    - [9505] Problem with the DirectShow grabber : can't be initialised.
    - [9516] Problem in the getValue methods in the vpImage class.
    - [9746] The displayPoint method of the vpDisplayOpenCV class doesn't work.
    - [10472] Bug in the visual features: can't select the good feature.
    - [10647] Delay in displaying image overlays
    - [10687] The GDI display is not detected with Visual Studio 2010
    - [10696] [CMake] VISP_DIR path conflict
    - [10697] CMake standard output vars
    - [10719] Compilation error in vpPlot
    - [10723] Compilation error in vpFFMPEG.cpp
    - [10748] PThread and Win32 Conflict
    - [10928] vpPlane: rayIntersection from 2 points
    - [10985] In vpPlot, 2D curve plotting starts with point (0,0)
              and not with the first specified point.