[graphics/collada-dom] Fix undefined reference to ftello64
Use regular ftello(3) instead of obscure ftello64, since the proper
_FILE_OFFSET_BITS on linux is already defined to 64. This avoids undefined
symbols on NetBSD.

Bump PKGREVISION.