[image/opencv] Disable ffmpeg that doesn't compile on FC8
ffmpeg support doesn't compile on FC8:
cvcap_ffmpeg.cpp:248: error: integer constant is too large for 'long' type

The problem comes from the INT64_C constant that appears in avcodec.h
from ffmpeg and doesn't seem to be defined anywhere.

Since no package in robotpkg uses ffmpeg, disable it for now.
Bumped revision.