[devel/ros-catkin] add missing pyparsing dependency
fix build-time error:
> ImportError: "from catkin_pkg.package import parse_package" failed: No module named 'pyparsing'